[package]
name = "variables"
version = "2.3.4"
authors = ["Silas Junior <seelaz@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"